# Generated by Django 3.1 on 2020-10-30 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0019_auto_20200718_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 30, 13, 37, 53, 727126)),
        ),
    ]
