# Generated by Django 3.1 on 2020-10-30 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20201030_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 30, 14, 16, 30, 521860)),
        ),
    ]
