# Generated by Django 3.1 on 2020-10-30 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0022_auto_20201030_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 30, 14, 22, 46, 615038)),
        ),
    ]
