# Generated by Django 3.1 on 2020-11-03 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0023_auto_20201030_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 14, 15, 50, 659713)),
        ),
    ]
