# Generated by Django 3.1 on 2020-11-03 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0024_auto_20201103_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 14, 46, 12, 553095)),
        ),
    ]
