# Generated by Django 3.1 on 2020-11-03 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0025_auto_20201103_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='Items_present',
            new_name='brand_service_available',
        ),
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 3, 16, 23, 3, 216477)),
        ),
    ]
