# Generated by Django 3.1 on 2020-11-04 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0027_auto_20201103_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 4, 11, 44, 3, 924770)),
        ),
    ]
