# Generated by Django 3.1 on 2020-11-05 07:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0028_auto_20201104_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serviceable_list_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.item')),
            ],
        ),
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 5, 12, 41, 17, 964270)),
        ),
        migrations.DeleteModel(
            name='Serviceable_items',
        ),
        migrations.AddField(
            model_name='serviceable_list_items',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop'),
        ),
    ]
