# Generated by Django 3.1 on 2020-11-11 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0030_auto_20201111_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 11, 20, 18, 18, 644503)),
        ),
    ]
