# Generated by Django 3.1 on 2020-11-12 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0031_auto_20201111_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='service_no',
            field=models.IntegerField(default=10000, max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 11, 54, 59, 223658)),
        ),
    ]
