# Generated by Django 3.1 on 2020-11-12 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0032_auto_20201112_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='shop',
        ),
        migrations.AddField(
            model_name='review',
            name='shop_pk',
            field=models.IntegerField(default=11),
        ),
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 12, 27, 11, 122016)),
        ),
    ]
