# Generated by Django 3.1 on 2020-11-12 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0033_auto_20201112_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 12, 13, 42, 11, 355155)),
        ),
    ]
