# Generated by Django 3.1 on 2020-12-12 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0034_auto_20201112_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 12, 17, 33, 2, 21679)),
        ),
    ]
